apiVersion: apps/v1
kind: Deployment
metadata:
  name: notat-api
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: notat-api
  template:
    metadata:
      labels:
        app: notat-api
    spec:
      containers:
      - name: notat-api
        image: docker.pkg.github.com/cx-devops-101/notes-app/notat-api:sha-55bdc02
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: 32Mi