name: notat-api-CD

on:
  push:
    branches: [ master ]
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Build with Gradle
        run: ./notat-api/gradlew build 

      - name: Verify build
        run: ls -l ./notat-api/build/ && ls -l ./notat-api/build/libs

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: cx-devops-101/notes-app/notat-api
          path: notat-api
          tag_with_sha: true
          push: ${{github.ref == 'refs/heads/master'}}