name: notat-api-CI

defaults:
  run:
    working-directory: notat-api

on:
  pull_request:
    branches: [ master ]
    paths: 
      - 'notat-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Build with Gradle
        run: ./gradlew build 
